// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async spendSummary() : Promise<Result<SpendSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spend_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setBudget(budget: Budget) : Promise<Result<SpendSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_budget", { budget }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async conversationSpend(conversationId: number) : Promise<Result<ConversationSpend, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_spend", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgents() : Promise<Agent[]> {
    return await TAURI_INVOKE("list_agents");
},
async getLedger(limit: number | null) : Promise<LedgerEntry[]> {
    return await TAURI_INVOKE("get_ledger", { limit });
},
/**
 * The task board — durable cards for delegated work, newest first.
 */
async getTasks(limit: number | null) : Promise<Task[]> {
    return await TAURI_INVOKE("get_tasks", { limit });
},
/**
 * Close a task card without reviewing it (cancel it, or set aside a blocked one): it
 * leaves the Work board but stays in history.
 */
async closeTask(id: string) : Promise<void> {
    await TAURI_INVOKE("close_task", { id });
},
/**
 * Mark a task that's ready for review as reviewed: it leaves the Work board and stays in
 * history as reviewed.
 */
async reviewTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a chat for good: its messages go, and tasks that ran in it stay in history without
 * their transcript. The chat an agent is working in can't be deleted until they finish; the
 * open chat, once deleted, gives way to a fresh one in the same folder.
 */
async deleteConversation(conversationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Keep copies of files the developer picked or dropped, to send with a message.
 */
async attachFiles(paths: string[]) : Promise<Result<Attachment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Keep a file the developer pasted (a screenshot, say), sent as base64.
 */
async attachData(name: string, data: string) : Promise<Result<Attachment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_data", { name, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget files attached to a message that was never sent (their chip was removed).
 */
async discardAttachments(attachments: Attachment[]) : Promise<void> {
    await TAURI_INVOKE("discard_attachments", { attachments });
},
/**
 * The start of a chat's text or HTML file, for its preview.
 */
async readAttachmentText(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_attachment_text", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Where an agent's tone dials start: a built-in agent's character, else neutral.
 */
async defaultTone(agentId: string) : Promise<Tone> {
    return await TAURI_INVOKE("default_tone", { agentId });
},
/**
 * Hand work to an agent as a task: it starts in a conversation of its own, or
 * waits its turn if the agent is busy.
 */
async startTask(agentId: string, prompt: string, dir: string | null, attachments: Attachment[]) : Promise<Result<Task, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_task", { agentId, prompt, dir, attachments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pick an interrupted task back up where it left off, in its own conversation.
 */
async resumeTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Quit for real: every agent session stops. (Closing the window doesn't.)
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
/**
 * Whether Starkline opens at login, in the background.
 */
async loginItemEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("login_item_enabled");
},
async setLoginItem(enabled: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_login_item", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Everything the task screen shows: the task, what it delegated, its history,
 * plan, checks, uncommitted changes and conversation.
 */
async getTaskDetail(id: string) : Promise<TaskDetail | null> {
    return await TAURI_INVOKE("get_task_detail", { id });
},
async listWorktrees() : Promise<Worktree[]> {
    return await TAURI_INVOKE("list_worktrees");
},
async setWorktreesEnabled(enabled: boolean) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_worktrees_enabled", { enabled });
},
async saveWorktreeSetup(project: string, setup: WorktreeSetup) : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_worktree_setup", { project, setup }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWorktree(id: string, force: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_worktree", { id, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deliveryInfo(id: string) : Promise<Result<DeliveryInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delivery_info", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardTaskFile(id: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_task_file", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitTask(id: string, input: CommitInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_task", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async draftDelivery(id: string, paths: string[], request: boolean, token: string) : Promise<Result<Draft, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("draft_delivery", { id, paths, request, token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDeliveryDraft(token: string) : Promise<void> {
    await TAURI_INVOKE("cancel_delivery_draft", { token });
},
async createTaskRequest(id: string, input: RequestInput) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task_request", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async codeReviews() : Promise<CodeReviews> {
    return await TAURI_INVOKE("code_reviews");
},
async refreshCodeReviews() : Promise<void> {
    await TAURI_INVOKE("refresh_code_reviews");
},
async seeCodeReview(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("see_code_review", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async askCodeReview(id: string, agentId: string) : Promise<Result<Task, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ask_code_review", { id, agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The readable diff of one changed file in a task's folder.
 */
async getTaskFileDiff(id: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task_file_diff", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether macOS lets Starkline show notifications. Async: macOS answers on its own thread.
 */
async macNotificationStatus() : Promise<Result<NotificationPermission, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mac_notification_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask macOS to allow notifications (it prompts only the first time), waiting for the developer's answer.
 */
async requestMacNotifications() : Promise<Result<NotificationPermission, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_mac_notifications") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What also reaches the developer as a notification on this Mac.
 */
async setMacNotifications(settings: MacNotifications) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_mac_notifications", { settings });
},
/**
 * Show a test notification the way real ones arrive, whatever the toggles say.
 */
async testMacNotification() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_mac_notification") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Notification Centre's record, newest first.
 */
async listNotifications(limit: number | null) : Promise<Notification[]> {
    return await TAURI_INVOKE("list_notifications", { limit });
},
async markNotificationsRead(ids: number[]) : Promise<void> {
    await TAURI_INVOKE("mark_notifications_read", { ids });
},
async markAllNotificationsRead() : Promise<void> {
    await TAURI_INVOKE("mark_all_notifications_read");
},
/**
 * Permission rules the developer granted (revoked ones too, when asked).
 */
async listPermissionRules(includeRevoked: boolean) : Promise<PermissionRule[]> {
    return await TAURI_INVOKE("list_permission_rules", { includeRevoked });
},
/**
 * Take back a rule: the calls it covered need approval again.
 */
async revokePermissionRule(id: number) : Promise<boolean> {
    return await TAURI_INVOKE("revoke_permission_rule", { id });
},
/**
 * Starkline's permission policy: every rule and whether it runs on its own,
 * asks first, or never runs on its own.
 */
async permissionPolicy() : Promise<PolicyRule[]> {
    return await TAURI_INVOKE("permission_policy");
},
/**
 * What Starkline can do with an agent on each kind of provider, as built.
 */
async providerCapabilities() : Promise<ProviderCapabilities[]> {
    return await TAURI_INVOKE("provider_capabilities");
},
/**
 * The models a provider offers, as its CLI lists them (asked off the main thread).
 */
async providerModels(engineId: string) : Promise<Result<ModelChoice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("provider_models", { engineId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * start | poll | cancel pointing at something on the page.
 */
async browserPicker(action: string) : Promise<Result<PickerResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_picker", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What's at a point on the simulator panel's picture, in the picture's pixels.
 */
async simulatorPoint(udid: string, name: string, x: number, y: number, width: number) : Promise<Result<SimulatorPoint, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_point", { udid, name, x, y, width }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The simulator panel's extra controls: recording, logs, appearance, location, push and the status bar.
 */
async simulatorExtra(udid: string, action: string, args: ExtraArgs) : Promise<Result<ExtraState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_extra", { udid, action, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The iOS simulators Xcode has, and whether taps can go through from here.
 */
async simulatorStatus() : Promise<SimulatorStatus> {
    return await TAURI_INVOKE("simulator_status");
},
async simulatorBoot(udid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_boot", { udid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async simulatorShutdown(udid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_shutdown", { udid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The device's screen now, as a base64 JPEG.
 */
async simulatorFrame(udid: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_frame", { udid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A tap where the developer clicked the screen, in the screenshot's pixels (`width` is the screenshot's).
 */
async simulatorTap(udid: string, name: string, x: number, y: number, width: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_tap", { udid, name, x, y, width }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A swipe where the developer dragged across the screen, in the screenshot's pixels.
 */
async simulatorSwipe(udid: string, name: string, fromX: number, fromY: number, toX: number, toY: number, width: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_swipe", { udid, name, fromX, fromY, toX, toY, width }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async simulatorType(udid: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_type", { udid, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async simulatorHome(udid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_home", { udid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the Simulator app on this device.
 */
async simulatorOpenApp(udid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("simulator_open_app", { udid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Place the built-in browser over its panel and show it. Async: the browser view is
 * made on the main thread, which this waits for.
 */
async browserShow(bounds: Bounds, zoom: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_show", { bounds, zoom }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hide the built-in browser (its panel closed, or something is drawn over it).
 */
async browserHide() : Promise<void> {
    await TAURI_INVOKE("browser_hide");
},
/**
 * Open what was typed in the address bar.
 */
async browserNavigate(url: string) : Promise<Result<BrowserPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_navigate", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * back | forward | reload | stop
 */
async browserGo(action: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_go", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The page the built-in browser is on.
 */
async browserPage() : Promise<BrowserPage> {
    return await TAURI_INVOKE("browser_page");
},
async devserverCandidates(folder: string) : Promise<Result<Candidates, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devserver_candidates", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devserverSelect(folder: string, selected: string, custom: string) : Promise<Result<Candidates, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devserver_select", { folder, selected, custom }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devserverStart(folder: string, option: string | null, command: string | null) : Promise<Result<Server, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devserver_start", { folder, option, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devserverStop(folder: string) : Promise<Result<Server, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devserver_stop", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devserverRestart(folder: string) : Promise<Result<Server, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devserver_restart", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devserverList() : Promise<Server[]> {
    return await TAURI_INVOKE("devserver_list");
},
async devserverLogs(folder: string) : Promise<Result<Output, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devserver_logs", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every reminder, soonest first.
 */
async listReminders() : Promise<Reminder[]> {
    return await TAURI_INVOKE("list_reminders");
},
/**
 * Set a reminder (no id) or change one; it's checked before it's saved.
 */
async saveReminder(input: ReminderInput) : Promise<Result<Reminder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_reminder", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Done with a reminder: a one-off is finished, a repeating one waits for its next time.
 */
async completeReminder(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_reminder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remind me again later.
 */
async snoozeReminder(id: number, until: number) : Promise<Result<Reminder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("snooze_reminder", { id, until }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteReminder(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_reminder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every automation, by name.
 */
async listAutomations() : Promise<Automation[]> {
    return await TAURI_INVOKE("list_automations");
},
/**
 * Create an automation (no id) or change one; it's checked before it's saved.
 */
async saveAutomation(input: AutomationInput) : Promise<Result<Automation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_automation", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause an automation or turn it back on (its next run counts from now).
 */
async setAutomationEnabled(id: number, enabled: boolean) : Promise<Result<Automation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_automation_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAutomation(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_automation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run an automation now, outside its schedule.
 */
async runAutomationNow(id: number) : Promise<Result<AutomationRun, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_automation_now", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Don't make up a missed run; wait for the next one.
 */
async skipMissedRun(id: number) : Promise<void> {
    await TAURI_INVOKE("skip_missed_run", { id });
},
/**
 * An automation's runs, newest first.
 */
async listAutomationRuns(id: number) : Promise<AutomationRun[]> {
    return await TAURI_INVOKE("list_automation_runs", { id });
},
/**
 * An agent's durable memory (the markdown it curates across sessions).
 */
async getMemory(agentId: string) : Promise<string> {
    return await TAURI_INVOKE("get_memory", { agentId });
},
/**
 * Inspect current prompt sections and provider instruction files without blocking the UI.
 */
async activeContext(agentId: string, folder: string, taskId: string | null) : Promise<Result<ActiveContext, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("active_context", { agentId, folder, taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Developer-clicked file actions are limited to files in the inspector.
 */
async openContextFile(agentId: string, folder: string, path: string, reveal: boolean, taskId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_context_file", { agentId, folder, path, reveal, taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bugs agents have reported about the app, newest first.
 */
async getBugs() : Promise<Bug[]> {
    return await TAURI_INVOKE("get_bugs");
},
/**
 * Change a bug's status (open | doing | fixed | wontfix).
 */
async setBugStatus(id: number, status: string) : Promise<void> {
    await TAURI_INVOKE("set_bug_status", { id, status });
},
/**
 * "Solve them now": hand the open bugs to the maintenance agent (DUM-E), which
 * works through them in the app's repo. Streams to DUM-E's chat tab; the bugs
 * are marked doing, then fixed when the run completes (reopen from the UI if not).
 */
async runMaintenance() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_maintenance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject() : Promise<string> {
    return await TAURI_INVOKE("get_project");
},
/**
 * Set the active/default project (adds it to the managed list if new).
 */
async setProject(path: string) : Promise<Result<ProjectsState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<ProjectsState> {
    return await TAURI_INVOKE("list_projects");
},
async addProject(path: string) : Promise<Result<ProjectsState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProject(path: string) : Promise<ProjectsState> {
    return await TAURI_INVOKE("remove_project", { path });
},
async spawnAgent(agentId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_agent", { agentId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalOpen(folder: string, cols: number, rows: number) : Promise<Result<TerminalInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_open", { folder, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalWrite(id: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalResize(id: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalClose(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_close", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalList() : Promise<TerminalInfo[]> {
    return await TAURI_INVOKE("terminal_list");
},
async terminalAttach(id: string, channel: TAURI_CHANNEL<TerminalOutput>) : Promise<Result<TerminalOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_attach", { id, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalTitle(id: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_title", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ptyWrite(agentId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pty_write", { agentId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ptyResize(agentId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pty_resize", { agentId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async killAgent(agentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Release Ultron containment for a Blocked agent (the "release" action).
 */
async unblockAgent(agentId: string) : Promise<void> {
    await TAURI_INVOKE("unblock_agent", { agentId });
},
/**
 * Notify-only check for a newer GitHub release (fail-loud; logs to updater.log).
 */
async checkUpdate() : Promise<void> {
    await TAURI_INVOKE("check_update");
},
/**
 * JARVIS routing: pick a free worker for a task, spawning one if needed, and
 * deliver the prompt to its session (in the current project directory).
 */
async dispatchTask(prompt: string, cols: number, rows: number) : Promise<Result<DispatchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_task", { prompt, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Agent-to-agent help: `from` pulls `to` into the same project to assist.
 * The helper spawns in the requester's working directory and receives context.
 */
async requestAssist(from: string, to: string, note: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_assist", { from, to, note, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Chat with an agent (headless Claude Code). Starts a session in `dir` (or the
 * agent's recorded workdir / current project) on first message.
 */
async chatSend(agentId: string, text: string, dir: string | null, attachments: Attachment[]) : Promise<Result<number | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_send", { agentId, text, dir, attachments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * End the agent's live session. Saved chats are never deleted here; starting a
 * fresh conversation is `new_chat`.
 */
async chatStop(agentId: string) : Promise<void> {
    await TAURI_INVOKE("chat_stop", { agentId });
},
/**
 * The persisted transcript for an agent's active conversation (for rehydration).
 */
async getChat(agentId: string, limit: number | null) : Promise<StoredMessage[]> {
    return await TAURI_INVOKE("get_chat", { agentId, limit });
},
/**
 * The agent's current saved chat, if it has one, so the UI can restore the folder
 * it runs in: resuming a Claude session only works from its own folder.
 */
async activeConversation(agentId: string) : Promise<Conversation | null> {
    return await TAURI_INVOKE("active_conversation", { agentId });
},
/**
 * All saved chats across agents, most-recently-active first.
 */
async listConversations() : Promise<Conversation[]> {
    return await TAURI_INVOKE("list_conversations");
},
/**
 * Start a fresh conversation with an agent (ends the live session so the next
 * message begins a genuinely new chat), in `cwd` (a project folder) or where the
 * agent works now. Returns the new conversation id.
 */
async newChat(agentId: string, cwd: string | null) : Promise<number> {
    return await TAURI_INVOKE("new_chat", { agentId, cwd });
},
/**
 * Reopen a saved conversation: make it active, end the live session, and point
 * the agent's workdir at the conversation's dir so the next message resumes it.
 */
async openConversation(conversationId: number) : Promise<void> {
    await TAURI_INVOKE("open_conversation", { conversationId });
},
/**
 * List files AND folders under `dir` (relative paths, recursively into every
 * subfolder) for the chat's `@` picker. Respects .gitignore and skips heavy
 * noise dirs, so it mirrors what Claude Code would see.
 */
async listFiles(dir: string, limit: number | null) : Promise<PathEntry[]> {
    return await TAURI_INVOKE("list_files", { dir, limit });
},
/**
 * Deliver the human's decision back to a blocked `ask_human` review.
 */
async reviewRespond(id: string, decision: string) : Promise<void> {
    await TAURI_INVOKE("review_respond", { id, decision });
},
/**
 * Everything agents are currently blocked on, oldest first.
 */
async pendingReviews() : Promise<ReviewRequest[]> {
    return await TAURI_INVOKE("pending_reviews");
},
/**
 * What the agent runtime can do right now: installed provider CLIs, the data
 * store and the agent bridge.
 */
async runtimeHealth() : Promise<RuntimeHealth> {
    return await TAURI_INVOKE("runtime_health");
},
async studioAvailable() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async studioDraw(choices: Choices, id: string | null, theme: string | null) : Promise<Result<Look, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_draw", { choices, id, theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async studioLooks() : Promise<Look[]> {
    return await TAURI_INVOKE("studio_looks");
},
async studioJob(id: string) : Promise<Result<Look, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async studioCancel(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_cancel", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async studioApply(agentId: string, id: string | null) : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("studio_apply", { agentId, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether Starkline is keeping this Mac awake, and why.
 */
async powerState() : Promise<PowerState> {
    return await TAURI_INVOKE("power_state");
},
/**
 * Allow (or stop allowing) Starkline to keep this Mac awake while agents work.
 */
async setKeepAwake(enabled: boolean) : Promise<PowerState> {
    return await TAURI_INVOKE("set_keep_awake", { enabled });
},
async setCaptureShortcut(enabled: boolean, shortcut: string) : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_capture_shortcut", { enabled, shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureError() : Promise<string | null> {
    return await TAURI_INVOKE("capture_error");
},
async hideCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizeCapture(height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_capture", { height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rememberCapture(agentId: string, project: string | null, reminder: boolean) : Promise<AppConfig> {
    return await TAURI_INVOKE("remember_capture", { agentId, project, reminder });
},
async openCaptureTask(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_capture_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the voices are downloaded (or downloading), and who is speaking.
 */
async voiceStatus() : Promise<VoiceStatus> {
    return await TAURI_INVOKE("voice_status");
},
/**
 * Download the voice model once, in the background; progress arrives as `voices://status`.
 */
async downloadVoices() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_voices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelVoiceDownload() : Promise<void> {
    await TAURI_INVOKE("cancel_voice_download");
},
/**
 * Delete the voice model and saved speech, and turn voices off.
 */
async removeVoices() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_voices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setVoiceSettings(settings: VoiceSettings) : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_voice_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Say something now in an agent's voice: a voice preview, or a message read aloud.
 */
async speakVoice(agentId: string, text: string, token: string, voice: Voice | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("speak_voice", { agentId, text, token, voice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSpeaking() : Promise<void> {
    await TAURI_INVOKE("stop_speaking");
},
/**
 * The agent whose chat is on screen, so its replies aren't read out while the developer reads them.
 */
async voiceChatVisibility(agentId: string | null) : Promise<void> {
    await TAURI_INVOKE("voice_chat_visibility", { agentId });
},
async getConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("get_config");
},
/**
 * Upsert an agent (edit an existing one by id, or add a new one).
 */
async updateAgent(agent: AgentConfig) : Promise<AppConfig> {
    return await TAURI_INVOKE("update_agent", { agent });
},
async removeAgent(id: string) : Promise<AppConfig> {
    return await TAURI_INVOKE("remove_agent", { id });
},
/**
 * Upsert an engine (edit by id, or add a new backend).
 */
async updateEngine(engine: EngineConfig) : Promise<AppConfig> {
    return await TAURI_INVOKE("update_engine", { engine });
},
async removeEngine(id: string) : Promise<AppConfig> {
    return await TAURI_INVOKE("remove_engine", { id });
},
async setOnboarded(value: boolean) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_onboarded", { value });
},
/**
 * Set the floor lighting mode ("auto" | "system" | morning/day/evening/night).
 */
async setLighting(mode: string) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_lighting", { mode });
},
/**
 * Change how Starkline looks and what the agents wear; nothing about the work changes with it.
 */
async setTheme(theme: string, outfits: string) : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme", { theme, outfits }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the standup mission cadence in minutes (0 = off).
 */
async setStandupMinutes(minutes: number) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_standup_minutes", { minutes });
},
/**
 * Restore the built-in engines + roster (wipes customizations).
 */
async resetConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("reset_config");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActiveContext = { agent_name: string; provider: string; model: string; sources: ContextSource[]; project_hint: string | null; notes: string[] }
/**
 * A member of the Starkline roster. `home_x`/`home_y` are tile coordinates
 * of the agent's desk on the pixel lab floor. `figure` selects the sprite
 * silhouette ("masc" | "fem" | "synth").
 */
export type Agent = { id: string; name: string; role: string; kind: AgentKind; engine: string; 
/**
 * Hex accent color for the pixel sprite.
 */
accent: string; figure: string; look?: string | null; home_x: number; home_y: number; status: AgentStatus }
/**
 * One roster member. `personality` is the editable system-prompt character;
 * app mechanics (delegation rules, the ask_human note) are appended in code.
 */
export type AgentConfig = { voice?: Voice | null; id: string; name: string; role: string; kind: AgentKind; accent?: string; 
/**
 * Sprite silhouette / pack ref ("masc" | "fem" | "synth" | custom id).
 */
figure?: string; look?: string | null; 
/**
 * Engine id this agent runs on (must match an EngineConfig.id).
 */
engine?: string; 
/**
 * Model override ("" = use the engine's default model).
 */
model?: string; 
/**
 * How hard the model thinks: one of the levels it takes ("" = the model's own default).
 */
effort?: string; 
/**
 * Editable character/system prompt.
 */
personality?: string; home_x: number; home_y: number; enabled?: boolean; 
/**
 * The agent may start temporary helpers of its own (its provider's subagents).
 */
helpers?: boolean; 
/**
 * The model those helpers use ("" = the provider's choice).
 */
helper_model?: string; 
/**
 * How the agent comes across (dials); filled with its default when missing.
 */
tone?: Tone | null }
export type AgentKind = "orchestrator" | "worker" | 
/**
 * Fixes bugs in THIS app that agents report — not a normal delegation target.
 */
"maintenance"
/**
 * Live status of an agent, drives the pixel sprite animation on the floor.
 */
export type AgentStatus = "offline" | "idle" | "thinking" | "working" | "blocked"
export type AppConfig = { voices?: VoiceSettings; version?: number; 
/**
 * Whether the user has completed (or skipped) the first-run setup wizard.
 */
onboarded?: boolean; 
/**
 * Floor lighting mode: "auto" (clock) | "system" | "morning" | "day" |
 * "evening" | "night".
 */
lighting?: string; 
/**
 * Standup mission cadence in minutes (0 = off). When set, a live
 * orchestrator is periodically nudged to review the board and re-engage
 * stalled workers — the "keeps working while you're away" autonomy.
 */
standup_minutes?: number; 
/**
 * The developer allows Starkline to keep this Mac awake while agents work.
 */
keep_awake?: boolean; mac_notifications?: MacNotifications; budget?: Budget; worktrees_enabled?: boolean; worktree_setup?: Partial<{ [key in string]: WorktreeSetup }>; 
/**
 * The global capture shortcut and the choices used in its small window.
 */
quick_capture?: CaptureConfig; 
/**
 * How Starkline looks: one of [`THEMES`]. Tasks, permissions and providers don't change with it.
 */
theme?: string; 
/**
 * What the agents wear: the active theme's outfits ("theme"), their own look in every
 * theme ("own"), or one theme's outfits (one of [`THEMES`]).
 */
outfits?: string; 
/**
 * The chosen dev command and custom command, per project folder.
 */
dev_servers?: Partial<{ [key in string]: Choice }>; engines: EngineConfig[]; agents: AgentConfig[] }
export type Attachment = { 
/**
 * Where the file is kept: Starkline's copy.
 */
path: string; name: string; 
/**
 * Its media type, e.g. "image/png".
 */
mime: string; kind: AttachmentKind; size: number }
/**
 * How a file previews in the chat.
 */
export type AttachmentKind = "image" | "video" | "audio" | "pdf" | "html" | 
/**
 * Markdown documents: shown rendered.
 */
"markdown" | 
/**
 * Plain text, data and source code.
 */
"text" | 
/**
 * Office and iWork documents, e-books: opened in their own app.
 */
"document" | "file"
/**
 * How an engine authenticates. `cli-login` = whatever the CLI is already logged
 * into on this machine; `api-key-env` = inject `env` vars (e.g. an API key) into
 * the spawned process; `none` = no auth needed.
 */
export type AuthConfig = { method?: string; 
/**
 * Environment variables to inject into the engine process (API keys etc.).
 */
env?: Partial<{ [key in string]: string }> }
/**
 * Work that runs on a schedule, owned by one agent in one folder.
 */
export type Automation = { id: number; name: string; agent_id: string; cwd: string; 
/**
 * What the owner is asked to do each run.
 */
instruction: string; schedule: Schedule; enabled: boolean; 
/**
 * When a run was missed (the Mac was asleep or Starkline closed): run_once | skip | ask
 */
missed: string; 
/**
 * failure | always | never
 */
notify: string; 
/**
 * A run that takes longer is stopped.
 */
max_minutes: number; 
/**
 * The developer wants the Mac woken for it (needs the wake helper).
 */
wake: boolean; created: number; updated: number; next_run: number | null; last_run: number | null; last_status: string | null }
/**
 * What the developer edits.
 */
export type AutomationInput = { 
/**
 * None to create a new automation.
 */
id: number | null; name: string; agent_id: string; cwd: string; instruction: string; schedule: Schedule; enabled: boolean; 
/**
 * run_once | skip | ask
 */
missed: string; 
/**
 * failure | always | never
 */
notify: string; max_minutes: number; wake: boolean }
/**
 * One run of an automation.
 */
export type AutomationRun = { id: number; automation_id: number; scheduled_for: number; started: number | null; finished: number | null; 
/**
 * running | succeeded | failed | missed | skipped
 */
status: string; task_id: string | null; summary: string; 
/**
 * What started it: schedule | late (a missed slot, made up) | you
 */
trigger: string }
/**
 * Where the panel is, in the window's own coordinates.
 */
export type Bounds = { x: number; y: number; width: number; height: number }
/**
 * The page as the panel shows it.
 */
export type BrowserPage = { 
/**
 * "" before anything has been opened.
 */
url: string; title: string; loading: boolean }
export type BrowserPick = { selector: string; tag: string; id: string; classes: string[]; role: string; accessible_name: string; text: string; attributes: Partial<{ [key in string]: string }>; styles: Partial<{ [key in string]: string }>; bounds: Bounds; url: string; title: string; viewport: Partial<{ [key in string]: number }>; device_pixel_ratio: number; outer_html: string }
export type Budget = { period: BudgetPeriod; limit_usd: number; warn_percent: number }
export type BudgetPeriod = "day" | "week" | "month"
/**
 * A bug in the app, reported by an agent for the maintenance agent to fix.
 */
export type Bug = { id: number; reporter: string; title: string; detail: string; 
/**
 * open | doing | fixed | wontfix
 */
status: string; created: number; updated: number }
export type Candidate = { id: string; label: string; command: string; cwd: string; env: Partial<{ [key in string]: string }>; port: number | null }
export type Candidates = { folder: string; options: Candidate[]; selected: string; custom: string }
export type Capability = { support: Support; 
/**
 * One plain sentence on what that means here.
 */
note: string }
export type CaptureConfig = { enabled: boolean; shortcut: string; last_agent: string | null; last_project: string | null; last_reminder_agent: string | null }
/**
 * The latest result of each distinct check.
 */
export type CheckRun = { kind: string; command: string; passed: boolean; at: number; duration_ms: number | null; agent_id: string }
export type Choice = { selected: string; custom: string }
export type Choices = { figure: string; options: Partial<{ [key in string]: string }>; note: string }
export type CodeReviewItem = { id: string; cwd: string; host_kind: HostKind; number: number; title: string; url: string; branch: string; head: string; 
/**
 * failed | changes | comments | review
 */
reason: string; updated: string; failed_checks: string[]; agent_id: string; task_id: string | null }
export type CodeReviews = { items: CodeReviewItem[]; connections: string[]; has_host: boolean }
export type CommitInput = { paths: string[]; message: string; branch: string | null; push: boolean }
export type ContextSource = { group: number; name: string; scope: string; delivery: string; accepted: boolean; conditional: boolean; path: string | null; characters: number; tokens: number; text: string; omitted_characters: number; markdown: boolean }
/**
 * A saved chat — one continuous conversation with an agent, resumable later.
 */
export type Conversation = { id: number; agent_id: string; title: string; cwd: string; created: number; updated: number; 
/**
 * A teammate's delegation ran here, not a chat the developer had.
 */
delegated: boolean; project_folder: string; branch: string }
export type ConversationSpend = { total: SpendTotal; context_tokens: number }
export type DeliveryInfo = { branch: string; default_branch: string; new_branch: string; host: Host | null; pushed: boolean; request_url: string | null; request_title: string }
export type DispatchResult = { agent_id: string; name: string; spawned: boolean }
export type Draft = { text: string; warning: string | null }
/**
 * A backend an agent can run on. `kind` selects the adapter (how we build the
 * command and parse its output); `command`/`extra_args` are the concrete CLI.
 */
export type EngineConfig = { id: string; label: string; 
/**
 * Adapter type: "claude-code" | "codex" | "opencode" | "generic-cli".
 */
kind: string; command: string; extra_args?: string[]; 
/**
 * Default model for this engine ("" = the engine's own default).
 */
model?: string; auth?: AuthConfig; 
/**
 * Whether this engine speaks our MCP bridge (delegation, ask_human, the
 * permission gate). Claude Code, Codex and OpenCode do through their
 * adapters; a generic CLI doesn't.
 */
supports_mcp?: boolean; enabled?: boolean }
export type EngineHealth = { id: string; label: string; kind: string; enabled: boolean; 
/**
 * The CLI was found on this Mac.
 */
installed: boolean; path: string | null; version: string | null; 
/**
 * Whether the CLI has credentials, as it reports itself; None until it has answered.
 */
signIn: SignIn | null }
export type ExtraArgs = { mode?: string | null; latitude?: number | null; longitude?: number | null; clear?: boolean | null; enabled?: boolean | null; bundle_id?: string | null; payload?: string | null; minutes?: number | null; predicate?: string | null; process?: string | null }
export type ExtraState = { recording: Recording | null; saved: Attachment | null; appearance: string; last_bundle: string; status_bar: boolean; logs: string }
/**
 * A file with uncommitted changes in the task's folder.
 */
export type FileChange = { path: string; 
/**
 * added | modified | deleted | renamed | untracked
 */
status: string; added: number | null; removed: number | null }
export type FileClaim = { workspace: string; path: string; agent_id: string; task_id: string | null; reason: string; exclusive: boolean }
export type Host = { kind: HostKind; hostname: string; repository: string; remote: string; connection: string | null }
export type HostKind = "github" | "gitlab" | "unknown"
export type LedgerEntry = { id: number; ts: number; agent_id: string; kind: string; detail: string; load: number }
export type Look = { id: string; choices: Choices; paths: Partial<{ [key in string]: string }>; progress: Partial<{ [key in string]: string }>; errors: Partial<{ [key in string]: string }>; revision: number; saved: boolean }
export type MacNotifications = { enabled?: boolean; in_front?: boolean; reminders?: boolean; requests?: boolean; work?: boolean; code_review?: boolean; automations?: boolean; budget?: boolean; checks?: boolean; claims?: boolean }
/**
 * A model an agent can run on.
 */
export type ModelChoice = { 
/**
 * What the provider is told ("gpt-5.6-sol", "anthropic/claude-sonnet-4-5", "claude-opus-5-5").
 */
id: string; name: string; 
/**
 * The provider's own default.
 */
default: boolean; 
/**
 * What it's for, in the provider's words ("" when it doesn't say).
 */
description: string; 
/**
 * The effort levels it takes, lowest first; empty when it has none to choose.
 */
efforts: string[]; 
/**
 * The level it runs at when the agent doesn't choose one, where the provider says.
 */
default_effort: string | null; 
/**
 * An older or less common model: offered under "More models" rather than up front.
 */
older: boolean }
/**
 * Something that needed or may interest the developer, kept until they archive it.
 */
export type Notification = { id: number; ts: number; 
/**
 * approval | question | review | task_ready | task_blocked | check_failed | rule_used
 */
kind: string; 
/**
 * needs_you | update
 */
urgency: string; agent_id: string; task_id: string | null; cwd: string; title: string; body: string; 
/**
 * The pending review it stands for, while it can still be answered.
 */
review_id: string | null; read: boolean; 
/**
 * When it was dealt with, and how ("Allowed once", "Answered", "Closed").
 */
handled: number | null; outcome: string | null; 
/**
 * The automation it's about (a missed or failed run).
 */
automation_id: number | null; 
/**
 * The reminder that went off.
 */
reminder_id: number | null }
export type NotificationPermission = { state: PermissionState; settings_url: string | null }
export type Output = { folder: string; generation: number; cursor: number; lines: string[] }
export type PathEntry = { path: string; dir: boolean }
/**
 * A stored rule, as Settings lists it.
 */
export type PermissionRule = { id: number; created: number; 
/**
 * task | project | everywhere
 */
scope: string; 
/**
 * For task rules: the task. For project rules: the project folder.
 */
task_id: string | null; project: string | null; tool: string; pattern: string; display: string; 
/**
 * The policy rule it loosens ("Install or update dependencies").
 */
rule: string; 
/**
 * "approval" or "never": how strongly the default held this back.
 */
tier: string; uses: number; last_used: number | null; revoked: number | null }
export type PermissionState = "allowed" | "denied" | "not_asked" | "provisional" | "system"
export type PickerResult = { active: boolean; pick: BrowserPick | null; attachment?: Attachment | null }
/**
 * One step of the owner's own plan (its to-do list).
 */
export type PlanItem = { content: string; 
/**
 * pending | in_progress | completed
 */
status: string; 
/**
 * How the step reads while it's being done ("Running the tests").
 */
active: string | null }
export type PointElement = { role: string; label: string; value: string; frame: Bounds }
/**
 * One rule of the policy, as the interface lists it.
 */
export type PolicyRule = { 
/**
 * The rule as the developer reads it ("Install or update dependencies").
 */
label: string; 
/**
 * automatic | approval | never
 */
tier: string }
export type PowerState = { 
/**
 * The developer allows Starkline to keep this Mac awake.
 */
enabled: boolean; 
/**
 * A power assertion is held right now.
 */
holding: boolean; 
/**
 * Why it is held, or why not, in plain words.
 */
reason: string; 
/**
 * False where keep-awake isn't available on this platform.
 */
supported: boolean }
export type ProjectInfo = { path: string; name: string }
export type ProjectsState = { projects: ProjectInfo[]; active: string }
export type ProviderCapabilities = { 
/**
 * claude-code | codex | opencode | generic-cli
 */
kind: string; label: string; 
/**
 * A chat continues where it left off, even after Starkline restarts.
 */
resume: Capability; 
/**
 * Starkline sees messages, commands, edits and plans as they happen.
 */
events: Capability; 
/**
 * Risky calls wait for Starkline's permission gate and your approval.
 */
approvals: Capability; 
/**
 * The provider confines the agent's commands with the operating system's sandbox.
 */
sandbox: Capability; 
/**
 * The agent can start temporary helpers of its own.
 */
helpers: Capability; 
/**
 * Starkline's team tools: delegate, ask you, message teammates, report bugs.
 */
team_tools: Capability }
export type Recording = { path: string; started: number }
/**
 * Something the developer wants reminding of, and the agent who reminds them.
 */
export type Reminder = { id: number; 
/**
 * What to remember ("Check the deploy").
 */
text: string; 
/**
 * The agent who reminds the developer.
 */
agent_id: string; 
/**
 * The task it's about, if any.
 */
task_id: string | null; 
/**
 * When it next goes off.
 */
due: number; 
/**
 * How it repeats; None goes off once.
 */
repeat: Schedule | null; 
/**
 * waiting (for its time) | due (went off, waiting on the developer) | done
 */
status: string; 
/**
 * When it last went off.
 */
fired: number | null; 
/**
 * Who set it: "you", or the agent the developer asked in chat.
 */
set_by: string; created: number; updated: number }
/**
 * What the developer enters.
 */
export type ReminderInput = { 
/**
 * None to create one.
 */
id: number | null; text: string; 
/**
 * Who reminds the developer.
 */
agent_id: string; task_id: string | null; 
/**
 * When it goes off. A repeating reminder goes off on its schedule instead.
 */
due: number; repeat: Schedule | null }
export type RequestInput = { title: string; body: string; base: string; draft: boolean }
/**
 * Something an agent is blocked on until the developer decides: a plan, diff,
 * question or choice (`ask_human`), or a command the permission gate routed.
 * Kept in app state while pending, so any screen (or a reloaded window) can
 * list it again.
 */
export type ReviewRequest = { id: string; agentId: string; title: string; body: string; 
/**
 * plan | diff | findings | questions | choice | mockup | command | permission
 */
kind: string; choices: string[]; 
/**
 * For `command`: the exact command line. For `permission`: the file, URL or input involved.
 */
command: string | null; 
/**
 * For `command` and `permission`: the folder the agent is working in.
 */
cwd: string | null; 
/**
 * For `command` and `permission`: the policy rule that stopped it.
 */
rule: string | null; 
/**
 * For `command` and `permission`: "approval" or "never" (never runs on its own).
 */
tier: string | null; 
/**
 * The task the agent is working on, if any.
 */
taskId: string | null; 
/**
 * For `command` and `permission`: what a rule from this request would allow
 * ("`npm install` commands"); None when no rule can safely cover it.
 */
grant: string | null; 
/**
 * For `command` and `permission`: the project a project-wide rule would apply to.
 */
project: string | null; 
/**
 * Unix ms when the agent asked.
 */
created: number }
export type RuntimeHealth = { 
/**
 * Where agent sessions run. "app": inside this window's process, so they
 * end when Starkline quits (until the standalone supervisor ships).
 */
host: string; engines: EngineHealth[]; 
/**
 * The local database answers queries.
 */
dataStore: boolean; 
/**
 * The socket agents use to delegate, ask and request approval is listening.
 */
bridge: boolean; 
/**
 * Why the bridge couldn't start, when it couldn't.
 */
bridgeError: string | null; 
/**
 * Provider sessions running right now.
 */
liveSessions: number; 
/**
 * Node.js, which runs the bridge every agent uses to delegate, ask and get
 * approval: its version, or None when it isn't installed.
 */
node: string | null; nodePath: string | null; 
/**
 * Agent sessions keep running with the window closed.
 */
background: boolean }
export type Schedule = 
/**
 * Every day at a local time ("HH:MM").
 */
{ kind: "daily"; time: string } | 
/**
 * Monday to Friday at a local time.
 */
{ kind: "weekdays"; time: string } | 
/**
 * One day a week (0 = Monday … 6 = Sunday) at a local time.
 */
{ kind: "weekly"; day: number; time: string } | 
/**
 * Every so many hours after the previous run.
 */
{ kind: "everyHours"; hours: number }
export type Server = { folder: string; command: string; status: Status; address: string | null; exit_code: number | null; generation: number; open_page: boolean }
/**
 * A provider CLI's own account of whether it can reach its models.
 */
export type SignIn = { signedIn: boolean; 
/**
 * How ("ChatGPT", "API key", "7 credentials"), when the CLI says.
 */
detail: string | null }
/**
 * A simulator Xcode has.
 */
export type SimDevice = { udid: string; name: string; 
/**
 * "iOS 26.0"
 */
runtime: string; booted: boolean }
export type SimulatorPoint = { device: string; x: number; y: number; element: PointElement | null }
export type SimulatorStatus = { 
/**
 * Xcode's simulator tools answered.
 */
available: boolean; 
/**
 * What's missing, when something is.
 */
problem: string | null; devices: SimDevice[]; 
/**
 * AXe or idb is installed, so taps, swipes and typing go through from Starkline.
 */
touch: boolean }
export type SpendDay = { date: string; total: SpendTotal }
export type SpendGroup = { key: string; total: SpendTotal }
export type SpendSummary = { today: SpendTotal; week: SpendTotal; month: SpendTotal; budget: Budget; budget_spend: number; days: SpendDay[]; agents: SpendGroup[]; projects: SpendGroup[]; models: SpendGroup[]; first_date: string | null; has_spend: boolean }
export type SpendTotal = { cost_usd: number; input_tokens: number; output_tokens: number; context_tokens: number; turns: number; unpriced_turns: number }
export type Status = "starting" | "running" | "stopped" | "crashed"
/**
 * One persisted chat turn — enough to rebuild the transcript UI on reopen.
 */
export type StoredMessage = { id: number; ts: number; role: string; text?: string | null; tool?: string | null; detail?: string | null; 
/**
 * Files with the message: what the developer attached, or what the agent made or shared.
 */
attachments: Attachment[] }
export type Support = "yes" | 
/**
 * Works in part (no built-in provider is limited today, but the interface shows it).
 */
"limited" | "no"
export type TAURI_CHANNEL<TSend> = null
/**
 * A unit of work with an accountable owner. The developer starts one from Work;
 * a delegation starts a child of the delegating agent's task. It is durable, so
 * in-flight and finished work survives the app closing.
 */
export type Task = { id: string; ts: number; updated: number; title: string; 
/**
 * The agent accountable for the work.
 */
assignee: string; 
/**
 * todo (queued) | doing | blocked | done (ready for review) | closed
 */
status: string; detail?: string | null; 
/**
 * The folder the task runs in ("" for tasks recorded before this existed).
 */
cwd: string; 
/**
 * The conversation the owner works on this task in.
 */
conversation_id: number | null; 
/**
 * The task this one was delegated from.
 */
parent_id: string | null; 
/**
 * Who asked for it: "you" (the developer) or the delegating agent's id.
 */
requested_by: string; 
/**
 * The full request, as asked.
 */
prompt: string; 
/**
 * The git branch checked out when the task started ("" outside a repository).
 */
branch: string; request_url: string | null; request_host: string | null; request_number: number | null; 
/**
 * When it started running, and when it stopped (finished, blocked or closed).
 */
started: number | null; finished: number | null; 
/**
 * The owner's own plan, as steps done out of steps total (from its to-do list).
 */
plan_done: number | null; plan_total: number | null; workspace_kind: string; project_folder: string }
/**
 * Everything the task screen shows.
 */
export type TaskDetail = { task: Task; children: Task[]; events: TaskEvent[]; plan: PlanItem[]; checks: CheckRun[]; 
/**
 * Uncommitted changes in the task's folder right now.
 */
changes: FileChange[]; 
/**
 * The branch checked out in the task's folder right now.
 */
branch: string | null; 
/**
 * The task's part of its owner's chat.
 */
messages: StoredMessage[]; workspace: WorkspaceInfo; claims: FileClaim[] }
/**
 * One thing that happened in a task, in order. Append-only.
 */
export type TaskEvent = { id: number; task_id: string; ts: number; agent_id: string; 
/**
 * created | queued | started | delegated | file | command | verification | plan | helper | approval | status
 */
kind: string; 
/**
 * One readable line.
 */
summary: string; 
/**
 * Kind-specific details as JSON ("" when there are none).
 */
data: string }
export type TerminalInfo = { id: string; folder: string; title: string; shell: string; alive: boolean; exit_code: number | null; program_running: boolean; note: string | null }
export type TerminalOutput = { data: number[]; offset: number; exit_code: number | null }
export type Tone = { 
/**
 * Serious (0) to playful.
 */
humour: number; 
/**
 * Earnest (0) to sarcastic.
 */
sarcasm: number; 
/**
 * Casual (0) to formal.
 */
formality: number; 
/**
 * Reserved (0) to upbeat.
 */
enthusiasm: number; 
/**
 * Brief (0) to thorough.
 */
detail: number }
export type Voice = { name: string; speed: number; pitch: number }
export type VoiceSettings = { enabled?: boolean; reminders?: boolean; ready?: boolean; needs_you?: boolean; failures?: boolean; replies?: boolean; background_only?: boolean; quiet_hours?: boolean; quiet_from?: string; quiet_to?: string; volume?: number }
export type VoiceStatus = { model: string; downloaded: number; total: number; agent_id: string | null; token: string | null; error: string | null }
export type WorkspaceInfo = { kind: string; path: string; project: string; branch: string; base: string; base_commit: string; decision: string; ahead: number; changes: FileChange[]; unmerged: string[]; removed: boolean; removable: boolean }
export type Worktree = { path: string; project: string; branch: string; base: string; base_commit: string; task_id: string; created: number; removed: number | null }
export type WorktreeSetup = { copy: string[]; command: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
