// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listAgents() : Promise<Agent[]> {
    return await TAURI_INVOKE("list_agents");
},
async getLedger(limit: number | null) : Promise<LedgerEntry[]> {
    return await TAURI_INVOKE("get_ledger", { limit });
},
/**
 * The task board — durable cards for delegated work, newest first.
 */
async getTasks(limit: number | null) : Promise<Task[]> {
    return await TAURI_INVOKE("get_tasks", { limit });
},
/**
 * An agent's durable memory (the markdown it curates across sessions).
 */
async getMemory(agentId: string) : Promise<string> {
    return await TAURI_INVOKE("get_memory", { agentId });
},
/**
 * Bugs agents have reported about the app, newest first.
 */
async getBugs() : Promise<Bug[]> {
    return await TAURI_INVOKE("get_bugs");
},
/**
 * Change a bug's status (open | doing | fixed | wontfix).
 */
async setBugStatus(id: number, status: string) : Promise<void> {
    await TAURI_INVOKE("set_bug_status", { id, status });
},
/**
 * "Solve them now": hand the open bugs to the maintenance agent (DUM-E), which
 * works through them in the app's repo. Streams to DUM-E's chat tab; the bugs
 * are marked doing, then fixed when the run completes (reopen from the UI if not).
 */
async runMaintenance() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_maintenance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject() : Promise<string> {
    return await TAURI_INVOKE("get_project");
},
/**
 * Set the active/default project (adds it to the managed list if new).
 */
async setProject(path: string) : Promise<Result<ProjectsState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<ProjectsState> {
    return await TAURI_INVOKE("list_projects");
},
async addProject(path: string) : Promise<Result<ProjectsState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeProject(path: string) : Promise<ProjectsState> {
    return await TAURI_INVOKE("remove_project", { path });
},
async spawnAgent(agentId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spawn_agent", { agentId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ptyWrite(agentId: string, data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pty_write", { agentId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ptyResize(agentId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pty_resize", { agentId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async killAgent(agentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Release Ultron containment for a Blocked agent (the "release" action).
 */
async unblockAgent(agentId: string) : Promise<void> {
    await TAURI_INVOKE("unblock_agent", { agentId });
},
/**
 * Notify-only check for a newer GitHub release (fail-loud; logs to updater.log).
 */
async checkUpdate() : Promise<void> {
    await TAURI_INVOKE("check_update");
},
/**
 * JARVIS routing: pick a free worker for a task, spawning one if needed, and
 * deliver the prompt to its session (in the current project directory).
 */
async dispatchTask(prompt: string, cols: number, rows: number) : Promise<Result<DispatchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dispatch_task", { prompt, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Agent-to-agent help: `from` pulls `to` into the same project to assist.
 * The helper spawns in the requester's working directory and receives context.
 */
async requestAssist(from: string, to: string, note: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_assist", { from, to, note, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Chat with an agent (headless Claude Code). Starts a session in `dir` (or the
 * agent's recorded workdir / current project) on first message.
 */
async chatSend(agentId: string, text: string, dir: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_send", { agentId, text, dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset button: end the live session AND wipe this agent's saved transcript +
 * resume pointer, so the next message starts a genuinely fresh conversation.
 */
async chatStop(agentId: string) : Promise<void> {
    await TAURI_INVOKE("chat_stop", { agentId });
},
/**
 * The persisted transcript for an agent's active conversation (for rehydration).
 */
async getChat(agentId: string, limit: number | null) : Promise<StoredMessage[]> {
    return await TAURI_INVOKE("get_chat", { agentId, limit });
},
/**
 * All saved chats across agents, most-recently-active first.
 */
async listConversations() : Promise<Conversation[]> {
    return await TAURI_INVOKE("list_conversations");
},
/**
 * Start a fresh conversation with an agent (ends the live session so the next
 * message begins a genuinely new chat). Returns the new conversation id.
 */
async newChat(agentId: string) : Promise<number> {
    return await TAURI_INVOKE("new_chat", { agentId });
},
/**
 * Reopen a saved conversation: make it active, end the live session, and point
 * the agent's workdir at the conversation's dir so the next message resumes it.
 */
async openConversation(conversationId: number) : Promise<void> {
    await TAURI_INVOKE("open_conversation", { conversationId });
},
/**
 * List files AND folders under `dir` (relative paths, recursively into every
 * subfolder) for the chat's `@` picker. Respects .gitignore and skips heavy
 * noise dirs, so it mirrors what Claude Code would see.
 */
async listFiles(dir: string, limit: number | null) : Promise<PathEntry[]> {
    return await TAURI_INVOKE("list_files", { dir, limit });
},
/**
 * Deliver the human's decision back to a blocked `ask_human` review.
 */
async reviewRespond(id: string, decision: string) : Promise<void> {
    await TAURI_INVOKE("review_respond", { id, decision });
},
async getConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("get_config");
},
/**
 * Upsert an agent (edit an existing one by id, or add a new one).
 */
async updateAgent(agent: AgentConfig) : Promise<AppConfig> {
    return await TAURI_INVOKE("update_agent", { agent });
},
async removeAgent(id: string) : Promise<AppConfig> {
    return await TAURI_INVOKE("remove_agent", { id });
},
/**
 * Upsert an engine (edit by id, or add a new backend).
 */
async updateEngine(engine: EngineConfig) : Promise<AppConfig> {
    return await TAURI_INVOKE("update_engine", { engine });
},
async removeEngine(id: string) : Promise<AppConfig> {
    return await TAURI_INVOKE("remove_engine", { id });
},
async setOnboarded(value: boolean) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_onboarded", { value });
},
/**
 * Set the floor lighting mode ("auto" | "system" | morning/day/evening/night).
 */
async setLighting(mode: string) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_lighting", { mode });
},
/**
 * Set the standup mission cadence in minutes (0 = off).
 */
async setStandupMinutes(minutes: number) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_standup_minutes", { minutes });
},
/**
 * Restore the built-in engines + roster (wipes customizations).
 */
async resetConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("reset_config");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A member of the Stark Tower roster. `home_x`/`home_y` are tile coordinates
 * of the agent's desk on the pixel lab floor. `figure` selects the sprite
 * silhouette ("masc" | "fem" | "synth").
 */
export type Agent = { id: string; name: string; role: string; kind: AgentKind; engine: string; 
/**
 * Hex accent color for the pixel sprite.
 */
accent: string; figure: string; home_x: number; home_y: number; status: AgentStatus }
/**
 * One roster member. `personality` is the editable system-prompt character;
 * app mechanics (delegation rules, the ask_human note) are appended in code.
 */
export type AgentConfig = { id: string; name: string; role: string; kind: AgentKind; accent?: string; 
/**
 * Sprite silhouette / pack ref ("masc" | "fem" | "synth" | custom id).
 */
figure?: string; 
/**
 * Engine id this agent runs on (must match an EngineConfig.id).
 */
engine?: string; 
/**
 * Model override ("" = use the engine's default model).
 */
model?: string; 
/**
 * Editable character/system prompt.
 */
personality?: string; home_x: number; home_y: number; enabled?: boolean }
export type AgentKind = "orchestrator" | "worker" | 
/**
 * Fixes bugs in THIS app that agents report — not a normal delegation target.
 */
"maintenance"
/**
 * Live status of an agent, drives the pixel sprite animation on the floor.
 */
export type AgentStatus = "offline" | "idle" | "thinking" | "working" | "blocked"
export type AppConfig = { version?: number; 
/**
 * Whether the user has completed (or skipped) the first-run setup wizard.
 */
onboarded?: boolean; 
/**
 * Floor lighting mode: "auto" (clock) | "system" | "morning" | "day" |
 * "evening" | "night".
 */
lighting?: string; 
/**
 * Standup mission cadence in minutes (0 = off). When set, a live
 * orchestrator is periodically nudged to review the board and re-engage
 * stalled workers — the "keeps working while you're away" autonomy.
 */
standup_minutes?: number; engines: EngineConfig[]; agents: AgentConfig[] }
/**
 * How an engine authenticates. `cli-login` = whatever the CLI is already logged
 * into on this machine; `api-key-env` = inject `env` vars (e.g. an API key) into
 * the spawned process; `none` = no auth needed.
 */
export type AuthConfig = { method?: string; 
/**
 * Environment variables to inject into the engine process (API keys etc.).
 */
env?: Partial<{ [key in string]: string }> }
/**
 * A bug in the app, reported by an agent for the maintenance agent to fix.
 */
export type Bug = { id: number; reporter: string; title: string; detail: string; 
/**
 * open | doing | fixed | wontfix
 */
status: string; created: number; updated: number }
/**
 * A saved chat — one continuous conversation with an agent, resumable later.
 */
export type Conversation = { id: number; agent_id: string; title: string; cwd: string; created: number; updated: number }
export type DispatchResult = { agent_id: string; name: string; spawned: boolean }
/**
 * A backend an agent can run on. `kind` selects the adapter (how we build the
 * command and parse its output); `command`/`extra_args` are the concrete CLI.
 */
export type EngineConfig = { id: string; label: string; 
/**
 * Adapter type: "claude-code" | "codex" | "opencode" | "generic-cli".
 */
kind: string; command: string; extra_args?: string[]; 
/**
 * Default model for this engine ("" = the engine's own default).
 */
model?: string; auth?: AuthConfig; 
/**
 * Whether this engine speaks our MCP bridge (delegation, ask_human, the
 * permission gate). Only Claude Code does today; others are basic until
 * their adapter is written.
 */
supports_mcp?: boolean; enabled?: boolean }
export type LedgerEntry = { id: number; ts: number; agent_id: string; kind: string; detail: string; load: number }
export type PathEntry = { path: string; dir: boolean }
export type ProjectInfo = { path: string; name: string }
export type ProjectsState = { projects: ProjectInfo[]; active: string }
/**
 * One persisted chat turn — enough to rebuild the transcript UI on reopen.
 */
export type StoredMessage = { id: number; ts: number; role: string; text?: string | null; tool?: string | null; detail?: string | null }
/**
 * A durable task card on the board. Delegations create one (`doing`) and close
 * it (`done` / `blocked`) so in-flight work is trackable across turns and
 * survives the UI closing — the flow upgrade munder-difflin's tasks.json gives.
 */
export type Task = { id: string; ts: number; updated: number; title: string; assignee: string; 
/**
 * todo | doing | blocked | done
 */
status: string; detail?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
